/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ros_aljacobson001
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        myMatrixPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myMatrixTable1 = new javax.swing.JTable();
        myGraphsPanel = new javax.swing.JPanel();
        myInduvidualPanel = new javax.swing.JPanel();
        pokeLabel = new javax.swing.JLabel();
        induvidualNameLabel = new javax.swing.JTextField();
        induvidualRaceLabel = new javax.swing.JTextField();
        induvidualGradeLabel = new javax.swing.JTextField();
        induvidualGenderLabel = new javax.swing.JTextField();
        induvidualBuildSeasonsLabel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        individualMatrixTable2 = new javax.swing.JTable();
        chartsTabbedPane2 = new javax.swing.JTabbedPane();
        induvidualChartPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPane.setPreferredSize(new java.awt.Dimension(800, 500));

        myMatrixTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student", "Skill Level", "Interest Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myMatrixTable1.setColumnSelectionAllowed(true);
        myMatrixTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(myMatrixTable1);
        myMatrixTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        myMatrixTable1.getColumnModel().getColumn(0).setResizable(false);
        myMatrixTable1.getColumnModel().getColumn(1).setResizable(false);
        myMatrixTable1.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout myMatrixPanelLayout = new javax.swing.GroupLayout(myMatrixPanel);
        myMatrixPanel.setLayout(myMatrixPanelLayout);
        myMatrixPanelLayout.setHorizontalGroup(
            myMatrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        myMatrixPanelLayout.setVerticalGroup(
            myMatrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("My Matrix", myMatrixPanel);

        javax.swing.GroupLayout myGraphsPanelLayout = new javax.swing.GroupLayout(myGraphsPanel);
        myGraphsPanel.setLayout(myGraphsPanelLayout);
        myGraphsPanelLayout.setHorizontalGroup(
            myGraphsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        myGraphsPanelLayout.setVerticalGroup(
            myGraphsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("My Graphs", myGraphsPanel);

        pokeLabel.setText("pokePic");

        induvidualNameLabel.setText("induvidualName");
        induvidualNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                induvidualNameLabelActionPerformed(evt);
            }
        });

        induvidualRaceLabel.setText("induvidualRace");

        induvidualGradeLabel.setText("induvidualGrade");
        induvidualGradeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                induvidualGradeLabelActionPerformed(evt);
            }
        });

        induvidualGenderLabel.setText("induvidualGender");
        induvidualGenderLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                induvidualGenderLabelActionPerformed(evt);
            }
        });

        induvidualBuildSeasonsLabel.setText("induvidualBuildSeasons");

        individualMatrixTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(individualMatrixTable2);

        javax.swing.GroupLayout induvidualChartPanelLayout = new javax.swing.GroupLayout(induvidualChartPanel);
        induvidualChartPanel.setLayout(induvidualChartPanelLayout);
        induvidualChartPanelLayout.setHorizontalGroup(
            induvidualChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        induvidualChartPanelLayout.setVerticalGroup(
            induvidualChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        chartsTabbedPane2.addTab("tab1", induvidualChartPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        chartsTabbedPane2.addTab("tab2", jPanel2);

        javax.swing.GroupLayout myInduvidualPanelLayout = new javax.swing.GroupLayout(myInduvidualPanel);
        myInduvidualPanel.setLayout(myInduvidualPanelLayout);
        myInduvidualPanelLayout.setHorizontalGroup(
            myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInduvidualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(myInduvidualPanelLayout.createSequentialGroup()
                        .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(induvidualNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInduvidualPanelLayout.createSequentialGroup()
                                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(induvidualGradeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(induvidualRaceLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(induvidualGenderLabel)
                                    .addComponent(induvidualBuildSeasonsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartsTabbedPane2)
                .addContainerGap())
        );
        myInduvidualPanelLayout.setVerticalGroup(
            myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInduvidualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartsTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(myInduvidualPanelLayout.createSequentialGroup()
                        .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(myInduvidualPanelLayout.createSequentialGroup()
                                .addComponent(induvidualNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(induvidualRaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(induvidualGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(myInduvidualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(induvidualGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(induvidualBuildSeasonsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainTabbedPane.addTab("My Individual", myInduvidualPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void induvidualGenderLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_induvidualGenderLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_induvidualGenderLabelActionPerformed

    private void induvidualGradeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_induvidualGradeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_induvidualGradeLabelActionPerformed

    private void induvidualNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_induvidualNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_induvidualNameLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
               
        /* Create and display the form */     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane chartsTabbedPane2;
    private javax.swing.JTable individualMatrixTable2;
    private javax.swing.JTextField induvidualBuildSeasonsLabel;
    private javax.swing.JPanel induvidualChartPanel;
    private javax.swing.JTextField induvidualGenderLabel;
    private javax.swing.JTextField induvidualGradeLabel;
    private javax.swing.JTextField induvidualNameLabel;
    private javax.swing.JTextField induvidualRaceLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel myGraphsPanel;
    private javax.swing.JPanel myInduvidualPanel;
    private javax.swing.JPanel myMatrixPanel;
    private javax.swing.JTable myMatrixTable1;
    private javax.swing.JLabel pokeLabel;
    // End of variables declaration//GEN-END:variables
}
